CREATE TABLE `kompetenser`.`COMPETENCE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `COMPETENCE_NAME` VARCHAR(45) NOT NULL,
  `CREATED_BY` INT NULL,
  `LAST_CHANGED_BY` INT NULL,
  `DESCRIPTION` VARCHAR(45) NULL,
  `DESCRIPTION_URL` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`, `COMPETENCE_NAME`),
  INDEX `CREATED_BY_FK_idx` (`CREATED_BY` ASC) VISIBLE,
  INDEX `LAST_CHANGED_BY_FK_idx` (`LAST_CHANGED_BY` ASC) VISIBLE,
  CONSTRAINT `CREATED_BY_FK`
    FOREIGN KEY (`CREATED_BY`)
    REFERENCES `kompetenser`.`USERACCOUNT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `LAST_CHANGED_BY_FK`
    FOREIGN KEY (`LAST_CHANGED_BY`)
    REFERENCES `kompetenser`.`USERACCOUNT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
    
INSERT INTO `kompetenser`.`COMPETENCE` (`COMPETENCE_NAME`, `CREATED_BY`, `LAST_CHANGED_BY`, `DESCRIPTION`, `DESCRIPTION_URL`) VALUES ('Java', '1', '1', 'Programming language', 'https://java.com');
INSERT INTO `kompetenser`.`COMPETENCE` (`COMPETENCE_NAME`, `CREATED_BY`, `LAST_CHANGED_BY`, `DESCRIPTION`, `DESCRIPTION_URL`) VALUES ('Python', '1', '1', 'Programming language', 'https://www.python.org/');