CREATE TABLE `kompetenser`.`EMPLOYMENT` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `EMPLOYMENT_DATE` DATETIME NULL,
  `EMPLOYMENT_END_DATE` DATETIME NULL,
  `USERACCOUNT_ID` INT NULL,
  `COMPANY_ID` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `COMPANY_ID_FK_idx` (`COMPANY_ID` ASC) VISIBLE,
  INDEX `USERACCOUNT_ID_FK_idx` (`USERACCOUNT_ID` ASC) VISIBLE,
  CONSTRAINT `USERACCOUNT_ID_FK`
    FOREIGN KEY (`USERACCOUNT_ID`)
    REFERENCES `kompetenser`.`USERACCOUNT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `COMPANY_ID_FK`
    FOREIGN KEY (`COMPANY_ID`)
    REFERENCES `kompetenser`.`COMPANY` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
    
INSERT INTO `kompetenser`.`EMPLOYMENT` (`EMPLOYMENT_DATE`, `USERACCOUNT_ID`, `COMPANY_ID`) VALUES ('2001-03-01', '1', '1');
INSERT INTO `kompetenser`.`EMPLOYMENT` (`EMPLOYMENT_DATE`, `USERACCOUNT_ID`, `COMPANY_ID`) VALUES ('1978-11-01', '2', '1');