CREATE TABLE `kompetenser`.`USERCOMPETENCE` (
  `USERACCOUNT_ID` INT NOT NULL,
  `COMPETENCE_ID` INT NOT NULL,
  `RATE` INT NULL,
  `SINCE_YEAR` INT NULL,
  PRIMARY KEY (`USERACCOUNT_ID`, `COMPETENCE_ID`),
  INDEX `COMPETENCE_ID_idx` (`COMPETENCE_ID` ASC) VISIBLE,
  INDEX `RATE` (`RATE` ASC) VISIBLE,
  CONSTRAINT `USERACCOUNT_ID`
    FOREIGN KEY (`USERACCOUNT_ID`)
    REFERENCES `kompetenser`.`USERACCOUNT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `COMPETENCE_ID`
    FOREIGN KEY (`COMPETENCE_ID`)
    REFERENCES `kompetenser`.`COMPETENCE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
    
INSERT INTO `kompetenser`.`USERCOMPETENCE` (`USERACCOUNT_ID`, `COMPETENCE_ID`, `RATE`, `SINCE_YEAR`) VALUES ('1', '1', '8', '2014');
INSERT INTO `kompetenser`.`USERCOMPETENCE` (`USERACCOUNT_ID`, `COMPETENCE_ID`, `RATE`, `SINCE_YEAR`) VALUES ('1', '2', '5', '2020');
INSERT INTO `kompetenser`.`USERCOMPETENCE` (`USERACCOUNT_ID`, `COMPETENCE_ID`, `RATE`, `SINCE_YEAR`) VALUES ('2', '1', '5', '1999');