CREATE TABLE `USERACCOUNT` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` VARCHAR(45) NOT NULL,
  `LAST_NAME` VARCHAR(45) NOT NULL,
  `USERNAME` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
  `EXPERIENCE_YEAR` INT DEFAULT NULL,
  `TITLE` VARCHAR(45) NOT NULL,
  `CITY_ID` int DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `CITY_ID` FOREIGN KEY (`ID`) REFERENCES `CITY` (`ID`));
  
INSERT INTO `kompetenser`.`USERACCOUNT` (`FIRST_NAME`, `LAST_NAME`, `USERNAME`, `PASSWORD`, `EXPERIENCE_YEAR`, `TITLE`, `CITY_ID`) VALUES ('Putte', 'Persson', 'puttep', 'abc', '2001', 'Carpenter', '1');
INSERT INTO `kompetenser`.`USERACCOUNT` (`FIRST_NAME`, `LAST_NAME`, `USERNAME`, `PASSWORD`, `EXPERIENCE_YEAR`, `TITLE`, `CITY_ID`) VALUES ('Anna', 'Andersson', 'annaa', '123', '1978', 'Director', '1');